version: "3"

services:
  realtime:
    build: .
    container_name: realtime-server
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: testdb
      DB_ENC_KEY: supabaserealtime
      DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
      REPLICATION_MODE: rls
      REPLICATION_POLL_INTERVAL: 100
      API_JWT_SECRET: dc447559-996d-4761-a306-f47a5eab1623
      SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
      ERL_AFLAGS: -proto_dist inet_tcp
      RLIMIT_NOFILE: 1000000
      DNS_NODES: "''"
      APP_NAME: realtime
